#!/bin/sh

#ディレクトリとデータベースの作成を行う

DIRPATH=$HOME"/check"
FILEPATH=$HOME"/check/CHECK_TIME"

check_nonactive() {
  if [ "$1" = "" ] ; then #$1が空文字列だと終了する
    echo "check requires function name!"
    exit
  fi
  return 0
}

check_database() {
  if [ ! -e $DIRPATH ] ; then
    mkdir $DIRPATH
  fi

  cd $DIRPATH

  if [ ! -e $FILEPATH ] ; then
    touch $FILEPATH
    sqlite3 CHECK_TIME "CREATE TABLE projects ('ID' INTEGER PRIMARY KEY AUTOINCREMENT, 'NAME' TEXT, 'START' INTEGER, 'END' INTEGER)"
  fi

  cd - > /dev/null
  return 0
}


#プログラムのステータスを確認する
check_status() {
    local projects_status=`sqlite3 CHECK_TIME "SELECT COUNT(*) FROM projects WHERE START = 1"`
    if [ $projects_status = 1 ] ; then
      ID_STATUS=`sqlite3 CHECK_TIME "SELECT ID FROM projects WHERE START = 1"`
      NAME_STATUS=`sqlite3 CHECK_TIME "SELECT NAME FROM projects WHERE ID == $ID_STATUS"`
      START_STATUS=`sqlite3 CHECK_TIME "SELECT START FROM projects WHERE ID == $ID_STATUS"`
      return 1
    elif [ $projects_status = 0 ] ; then 
      return 0
    else
      sqlite3 CHECK_TIME "SELECT NAME FROM projects WHERE START = 1"
      exit
    fi
}

#プロジェクトの存在を確認する
check_project() {
  local table_status=`sqlite3 CHECK_TIME "SELECT COUNT(*) FROM projects WHERE NAME = '$2'"`
  if [ $table_status = 1 ] ; then
    return 0
  elif [ $table_status = 0 ] ; then
    return 1
  fi
}

#プロジェクトの作成を行う
create_project() {
  sqlite3 CHECK_TIME "INSERT INTO projects ('NAME') VALUES ('$2')"
  sqlite3 CHECK_TIME "CREATE TABLE $2 ('ID' INTEGER PRIMARY KEY AUTOINCREMENT, 'START' DATETIME, 'END' DATETIME, 'MEMO' TEXT)"
  return 0
}


#チェックインする
check_in() {
  check_status
  local check_status_return=$?
  if [ $check_status_return = 0 ] ; then #実行状態check_status_return=0だった場合、最後にOUTされているので、INできる
    if [ -z "$2" ] ; then #projectが空文字列だと終了する
    echo "Please write a project name!"
    exit
    fi

    #テーブルの存在の確認
    check_project $1 $2
    local check_project_return=$?
    if [ $check_project_return = 1 ] ; then #check_project_return=1だった場合、テーブルは存在しないので、projectsへの追加とprojectの作成を行う
      create_project $1 $2
    fi

    #チェックインを行う
    local in_time=`date "+%Y-%m-%d %H:%M:%S"`
    echo "You can describe details of this activity! "
    printf "entry: "
    read memo
    sqlite3 CHECK_TIME "UPDATE projects SET START = 1 WHERE NAME = '$2'"
    sqlite3 CHECK_TIME "INSERT INTO $2 ('START', 'MEMO') VALUES ('$in_time', '$memo')"

    echo "Your check-in $2 is successful."
  
  elif [ $check_status_return = 1 ] ; then #実行状態check_status_return=1だった場合、最後はINなのでINできない
    echo "$NAME_STATUS is running. Please check out!"
    exit
  fi

  return 0
}

#データベースからINとOUTの時間の差分の秒数を抜き出し、HH:MM:SSの形式で表示する。
substraction_time() {
  local get_time=`sqlite3 CHECK_TIME "SELECT STRFTIME('%s', END) - STRFTIME('%s', START) FROM $NAME_STATUS WHERE ID = $query_id"`
  HOURS=`expr $get_time / 3600`
  MINUTE=`expr \( $get_time % 3600 \) / 60`
  SECOND=`expr $get_time % 60`
  # echo "Your check-out $NAME_STATUS is successful. This time is $hours:$minute:$second."
  return 0
}

#チェックアウトする。
check_out() {
  check_status
  local check_status_return=$?
  if [ $check_status_return = 1 ] ; then #実行状態check_status_return=1だった場合、最後はINなのでOUTする

    #チェックアウトする
    local out_time=`date "+%Y-%m-%d %H:%M:%S"`
    local query_id=`sqlite3 CHECK_TIME "SELECT ID FROM $NAME_STATUS WHERE END IS NULL"`
    if [ -z "$query_id" ] ; then
      query_id=`sqlite3 CHECK_TIME "SELECT ID FROM '$NAME_STATUS' WHERE ID = (SELECT max(ID) FROM '$NAME_STATUS')"`
    else
      sqlite3 CHECK_TIME "UPDATE $NAME_STATUS SET END = '$out_time' WHERE ID = '$query_id'"
    fi
    sqlite3 CHECK_TIME "UPDATE projects SET START = 0 WHERE NAME = '$NAME_STATUS'"
    substraction_time  $NAME_STATUS $query_id
    echo "Your check-out $NAME_STATUS is successful. This time is $HOURS:$MINUTE:$SECOND."

  elif [ $check_status_return = 0 ] ; then #実行状態check_status_return=1だった場合、最後はOUTなのでOUTできない
    echo "No projects is running!"
    exit
  fi
  return 0
}


check_stop() {
  check_status
  local check_status_return=$?
  if [ $check_status_return = 1 ] ; then #実行状態check_status_return=1だった場合、最後はINなのでOUTする

    #ストップする
    local stop_time=`date "+%Y-%m-%d %H:%M:%S"`
    local query_id=`sqlite3 CHECK_TIME "SELECT ID FROM $NAME_STATUS WHERE END IS NULL"`
    if [ ! -z "$query_id" ] ; then
      sqlite3 CHECK_TIME "UPDATE $NAME_STATUS SET END = '$stop_time' WHERE ID = '$query_id'"
      echo "$NAME_STATUS is stopping"
    else
        echo "$NAME_STATUS is already stopped!"
        exit
    fi

  elif [ $check_status_return = 0 ] ; then #実行状態check_status_return=0だった場合、最後はOUTなのでOUTできない
    echo "No projects is running!"
    exit
  fi
  return 0
}

check_resume() {
  check_status
  local check_status_return=$?
  if [ $check_status_return = 1 ] ; then
    local count_stop=`sqlite3 CHECK_TIME "SELECT COUNT(*) FROM '$NAME_STATUS' WHERE END IS NULL"`
      if [ $count_stop = 0 ]; then
        local resume_time=`date "+%Y-%m-%d %H:%M:%S"`
        local memo=`sqlite3 CHECK_TIME "SELECT MEMO FROM '$NAME_STATUS' WHERE ID = (SELECT max(ID) FROM '$NAME_STATUS')"`
        sqlite3 CHECK_TIME "INSERT INTO $NAME_STATUS ('START', 'MEMO') VALUES ('$resume_time', '$memo')"
        echo "$NAME_STATUS is resumed."
      else
        echo "$NAME_STATUS is already running!"
        exit
      fi

  
  elif [ $check_status_return = 0 ] ; then #実行状態check_status_return=1だった場合、最後はINなのでINできない
    echo "No projects is running!"
    exit
  fi

  return 0
}


check_list() {
  sqlite3 CHECK_TIME "SELECT NAME FROM projects"
  return 0
}

check_now() {
  check_status
  local check_status_return=$?
  if [ $check_status_return = 0 ] ; then
    echo "NOW no project is runnig!"
  elif [ $check_status_return = 1 ] ; then
    echo "Now $NAME_STATUS is running!"
  fi
  return 0
}

check_alter() {
  check_project $1 $2
  local check_project_return=$?
  if [ $check_project_return = 0 ] ; then #check_project_return=0だった場合、プロジェクトはは存在するのでプロジェクトの変更を行う。
    check_status
    local check_status_return=$?
    if [ $check_status_return = 1 ] ; then
      if [ $NAME_STATUS = $2 ] ; then
        #チェックアウトする
        local out_time=`date "+%Y-%m-%d %H:%M:%S"`
        local query_id=`sqlite3 CHECK_TIME "SELECT ID FROM $NAME_STATUS WHERE END IS NULL"`
        sqlite3 CHECK_TIME "UPDATE $NAME_STATUS SET END = '$out_time' WHERE ID = '$query_id'"
        sqlite3 CHECK_TIME "UPDATE projects SET START = 0 WHERE NAME = '$NAME_STATUS'"
      fi
    fi
    # ENDの値が更新されているので取得する
    local start_project=`sqlite3 CHECK_TIME "SELECT START from '$2'  WHERE ID = (SELECT max(ID) FROM '$2')"`
    local end_project=`sqlite3 CHECK_TIME "SELECT END from '$2'  WHERE ID = (SELECT max(ID) FROM '$2')"`
    #レコードの確認を行う
    echo "The latest record : "
    sqlite3 CHECK_TIME "SELECT START, END, MEMO from '$2' WHERE ID = (SELECT max(ID) FROM '$2')"
    echo "Please write project time from START (HH:MM:SS) : "
    read input_time
    local addtime="+$input_time"
    #$3をsqlに渡してENDの候補を表示させる
    local condidate=`sqlite3 CHECK_TIME "SELECT DATETIME(START, '$addtime') AS time FROM '$2' WHERE ID = (SELECT max(ID) FROM '$2')"`
    echo "END_TIME will alter :"
    echo "$end_project -> $condidate"
    echo "Do you alter this record?(y/n)."
    read alter_repry
    if [ $alter_repry = 'y' ] ; then
    sqlite3 CHECK_TIME "UPDATE '$2' SET END = '$condidate' WHERE ID = (SELECT max(ID) FROM '$2')"
    echo "altering $2 is successful."
    sqlite3 CHECK_TIME "SELECT START, END, MEMO from '$2' WHERE ID = (SELECT max(ID) FROM '$2')"

    else
       echo "altering is failed."
      exit
    fi

  else
    echo "$2 is not exist."
    exit
  fi
  return 0
}

check_drop() {
  check_project $1 $2
  local check_project_return=$?
  if [ $check_project_return = 0 ] ; then #check_project_return=0だった場合、プロジェクトはは存在するのでプロジェクトの削除を行う。
    sqlite3 CHECK_TIME "DROP TABLE '$2'"
    sqlite3 CHECK_TIME "DELETE FROM projects WHERE NAME = '$2'"
    echo "$2 is dropped."
  else
    echo "$2 is not exist."
    exit
  fi
  return 0
}

check_delete() {
  check_project $1 $2
  local check_project_return=$?
  if [ $check_project_return = 0 ] ; then #check_project_return=0だった場合、プロジェクトはは存在するのでプロジェクトの削除を行う。
    sqlite3 CHECK_TIME "SELECT * from '$2' WHERE ID = (SELECT max(ID) FROM '$2')"

    echo "Do you delete this record?(y/n)."
    read delete_repry
    if [ $delete_repry = 'y' ] ; then
      sqlite3 CHECK_TIME "DELETE FROM '$2' WHERE ID = (SELECT max(ID) FROM '$2')"
      echo "the record is deleted."
      sqlite3 CHECK_TIME "UPDATE projects SET START = 0 WHERE NAME = '$2'"
    else
      echo "deleting is failed."
      exit
    fi

  else
    echo "$2 is not exist."
    exit
  fi
  return 0
}

check_dump() {
  echo ".dump" | sqlite3 CHECK_TIME > CHECK_TIME.dump
  echo "creating dump file!"
  return 0
}

check_restore() {
    sqlite3 CHECK_TIME < CHECK_TIME.dump
    echo "reading CHECK_TIME.dump to CHECK_TIME"
    return 0
}

check_total() {
  check_project $1 $2
  local check_project_return=$?
  if [ $check_project_return = 0 ] ; then 
    check_status $1 $2
    local check_status_return=$?
    if [ $check_status_return = 1 ] ; then #実行状態check_status_return=1だった場合、プロジェクトにINしているのでチェックアウトするように指示を出す。
      if [ $NAME_STATUS = $2 ] ; then
        echo "$2 is running. Please check-out."
        exit
      fi
    fi
    local total_time=`sqlite3 CHECK_TIME "SELECT sum(STRFTIME('%s', END) - STRFTIME('%s', START)) FROM '$2'"`
    local hours=`expr $total_time / 3600`
    local minute=`expr \( $total_time % 3600 \) / 60`
    local second=`expr $total_time % 60`
    echo "$2 total activity time is $hours:$minute:$second."
  else
    echo "$2 is not exist."
    exit
  fi
  return 0
}

check_view() {
  check_project $1 $2
  local check_project_return=$?
  if [ $check_project_return = 0 ] ; then 
    check_status $1 $2
    local check_status_return=$?
    if [ $check_status_return = 1 ] ; then #実行状態check_status_return=1だった場合、プロジェクトにINしているのでチェックアウトするように指示を出す。
      if [ $NAME_STATUS = $2 ] ; then
        echo "$2 is running. Please check-out."
        exit
      fi
    fi
    sqlite3 CHECK_TIME "select DATE(START) AS date, TIME(SUM(STRFTIME('%s', END) - STRFTIME('%s', START)), 'unixepoch') AS time FROM '$2' GROUP BY date"
  else
    echo "$2 is not exist."
    exit
  fi
  return 0
}

check_show() {
  if [ -z "$2" ] ; then #$2の指定がない場合は全てのプロジェクトを表示する
    local VAR=`check_list  | sed -e "s/[\r\n]\+//g"`
    local projects=(`echo $VAR`)
    local sql=""
    local num=0
    for project in ${projects[@]}; do
      if [ $num = 0 ] ; then
        sql=${sql}"SELECT '$project', START, END, MEMO FROM '$project'"
      else
      sql="${sql} UNION SELECT '$project', START, END, MEMO FROM '$project'"
      fi
      num=$num+1
    done
    sql=${sql}" ORDER BY START ASC;"
    # echo $sql
    sqlite3 CHECK_TIME "${sql}"
  else #$2にプロジェクト名を指定するとそのプロジェクトだけどSELECTする
      check_project $1 $2
      local check_project_return=$?
      if [ $check_project_return = 0 ] ; then #check_project_return=0だった場合、プロジェクトはは存在する。
        sqlite3 CHECK_TIME "SELECT START, END, MEMO FROM '$2'"
      else
        echo "$2 is not exist."
        exit
    fi
  fi
  return 0
}

check_man() {
  echo ""
  echo "  check is a easy time logger tool."
  echo ""
  echo "    check has some functions."
  echo "      check in [project] : You can start logging time."
  echo "      check out : You can finish time logging."
  echo "      check stop : You can temporarily stop  time logging."
  echo "      check resume : You can resume time logging."
  echo "      check list : You can see lists of all projects."
  echo "      check now : You can see which project is running."
  echo "      check total [project] : You can see total time of a project."
  echo "      check view [project] : You can see total time of each day of a project."
  echo "      check show [none or project] : You can see the list of logs and also choose a project."
  echo "      check alter [project] : You can alter the latest record END_TIME of a project."
  echo "      check drop [project] : You can drop a project."
  echo "      check delete [project] : You can delete a latest record from a project."
  echo "      check dump : You can make a dumpfile."
  echo "      check restore : You can restore from a dumpfile."
  echo "      check man : You can see this command mannual."
  echo ""
  return 0
}

#スクリプトの流れ
##データベースの存在確認
##実行状態の確認
###チェックイン
####テーブルの存在確認
###チェックアウト
####時間計算
main() {
  #$1がないなら終了する
  check_nonactive $1
  #コマンドの実行環境の確認
  check_database

  #$HOME/checkに移動する
  cd $DIRPATH
  #実行状態の確認
  if [ $1 = "in" ] ; then
    check_in  $1 $2

  elif [ $1 = "out" ] ; then
    check_out

  elif [ $1 = "stop" ] ; then
    check_stop $1 $2

  elif [ $1 = "resume" ] ; then
    check_resume $1 $2

  elif [ $1 = "list" ] ; then
    check_list

  elif [ $1 = "now" ] ; then
    check_now

  elif [ $1 = "total" ] ; then
    check_total $1 $2

  elif [ $1 = "view" ] ; then
    check_view $1 $2

  elif [ $1 = "show" ] ; then
    check_show $1 $2

  elif [ $1 = "alter" ] ; then
    check_alter $1 $2

  elif [ $1 = "drop" ] ; then
    check_drop $1 $2

  elif [ $1 = "delete" ] ; then
    check_delete $1 $2

  elif [ $1 = "dump" ] ; then
    check_dump

  elif [ $1 = "restore" ] ; then
    check_restore

  elif [ $1 = "man" ] ; then
    check_man
  fi

  #元のディレクトリに移動する
  cd - > /dev/null
}

main $1 $2